import "../styles/globals.css";
import { ScrollProvider } from "../context/ScrollProvider"; // adjust path if needed

export const metadata = {
  title: "UNCVRD - Uncovering Visuals from your Vision.",
  description: "Generated by create next app",
  // icons: {
  //   icon: "/logo.ico",
  // },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <ScrollProvider>{children}</ScrollProvider>
      </body>
    </html>
  );
}
