import "../styles/globals.css";

export const metadata = {
  title: "UNCVRD - Uncovering Visuals from your Vision.",
  description: "Generated by create next app",
  // icons: {
  //   icon: "/logo.ico",
  // },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
